### ISSUE TITLE
pretrained model

### ISSUE THREAD

**Issue by ostwind** [kyungyunlee/sampleCNN-pytorch#1]
Hi Kyungyun!

Thank you for implementing the model in PyTorch, the much more research friendly framework :) . I'm wondering if you have reproduced the results in the paper, and if a pretrained model already exists?

**Comment by kyungyunlee** [comment]
Hi, I am sorry to be this late!!
No I don't have the pretrained model since I wasn't reproducing the results..
Hope you figured out how to do it :)
