### ISSUE TITLE
initialization

### ISSUE THREAD

**Issue by gabrieldernbach** [kyungyunlee/sampleCNN-pytorch#2]
Did you experiment with initialization?

The keras implementation of the authors performs the following which is different from the default torch initialization.

https://github.com/tae-jun/sampleaudio/blob/master/lib/initialization.py

**Comment by kyungyunlee** [comment]
Sorry I am very late!
I didn't experiment with initialization. This was more for testing the results and training the model myself. 
If you want exact replication of the results, please follow the paper!
